"""empty message

Revision ID: 90624332cd81
Revises: 4d9534f1dd04
Create Date: 2025-11-04 10:59:57.684244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90624332cd81'
down_revision: Union[str, Sequence[str], None] = '4d9534f1dd04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car', 'year',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car', 'year',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
